---
apiVersion: v1
kind: Secret
metadata:
  name: disconnected-registry-pull-secret
  namespace: sno2
stringData:
  .dockerconfigjson: '{"auths":{"quay.rhoso.bootcamp.lab:8443":{"auth":"xxxx"},"registry.redhat.io":{"auth":"xxxxx"}}}'
  type: kubernetes.io/dockerconfigjson

