---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "5glab"
  namespace: "5glab"
spec:
  # The base domain used by our SNOs
  baseDomain: "rhoso.bootcamp.lab"
  # The secret name of the secret containing the pull secret for our disconnected registry
  pullSecretRef:
    name: "disconnected-registry-pull-secret"
  # The OCP release we will be deploying otherwise specified (this can be configured per cluster as well)
  clusterImageSetNameRef: "active-ocp-version"
  # The ssh public key that will be injected into our SNOs authorized_keys
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCx4mhicRuaa3cpT+KGgz/TNoHz77EQ1uA2LivmC8j0cz65BQ/YghmndIWVt/rzVuj/+nyHEgXft+kT1Fk7iKwmhCkHT71eZlfaNseynFRRq79fLBlgLeCqKlpxurQ5rMBN2EwvJN8y8u5Sf5IT0WhEzHTOniiQZLBzEg56EDRtjgELtGObzMJKzWp2nuRyWP6AAX8Dp29LTnnus2SbLNjcO52ePQ6PoYBmSeMk56Gpgg8SAP3XxJKSO5zarruyKG+sXRRFO1kIp+i5PGTM5B6w5PNxPc9aNYPwYetRDkb07Gz7hnMI7e7GRIMmTfplS9//N/5syQmZokx9bKHXNZk/lCXa81uvElmhDY07U3oRr1ExhX9zGTcgUmMyLh43iPV+8FgSyKfLjZP+6IQF+/IEygg7LOevsPyVgKEm3Fy47WF3278t4UwlLaHw06i0yNWJKhkV4WaDbdhcNUWTijTUFO5MVxZmAdYfG1ddqjP5gBGl+THhnm9/FHHxoXZ0nbT77FX1OhFfFM+FlRHi1MbasXaccT0xJ13sC38aAuaw6DUoXKQuA+zwbTojkNZryBC1jHpDSPyKaTmPMQVT1qEFrTaqSR3D33ckNXhH1ZaxtPSGjU7eIE16WlZAGOhFytF8A+5el8ZmvQYKFdkNyAIdiFczg/eTuBnAVCG/OM1o7w== root@bastion"
  clusters:
  - clusterName: "sno2"
    # The sdn plugin that will be used
    networkType: "OVNKubernetes"
    # extraManifestPath: sno2-extra-manifest
    # Cluster labels (this will be used by RHACM)
    clusterLabels:
      common: "ocp416"
      logicalGroup: "active"
      group-du-sno: ""
      du-site: "sno2"
      du-zone: "europe"
    # Pod's SDN network range
    clusterNetwork:
      - cidr: "10.128.0.0/14"
        hostPrefix: 23
    # Network range where the SNO is connected
    machineNetwork:
      - cidr: "192.168.123.0/24"
    # Services SDN network range
    serviceNetwork:
      - "172.30.0.0/16"
    # cpuPartitioningMode: AllNodes
    additionalNTPSources:
      - ntp.rhoso.bootcamp.lab
    # holdInstallation: false
    nodes:
      - hostName: "sno2.rhoso.bootcamp.lab"
        role: "master"
        # We can add custom labels to our nodes, these will be added once the node joins the cluster
        nodeLabels:
          5gran.lab/my-custom-label: ""
        bmcAddress: "redfish-virtualmedia://192.168.123.1:9000/redfish/v1/Systems/local/sno2"
        # The secret name of the secret containing the bmc credentials for our bare metal node
        bmcCredentialsName:
          name: "sno2-bmc-credentials"
        # The MAC Address of the NIC from the bare metal node connected to the machineNetwork
        bootMACAddress: "AA:AA:AA:AA:03:01"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/vda
        nodeNetwork:
          interfaces:
            - name: enp1s0
              macAddress: "AA:AA:AA:AA:03:01"
          config:
            interfaces:
              - name: enp1s0
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  dhcp: true
                ipv6:
                  enabled: false
