apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index
  namespace: openshift-marketplace
spec:
  image: quay.rhoso.bootcamp.lab:8443/redhat/redhat-operator-index:v4.16
  sourceType: grpc
