---
apiVersion: v1
kind: Secret
metadata:
  name: disconnected-registry-pull-secret
  namespace: sno2
stringData:
  .dockerconfigjson: '{"auths":{"quay.rhoso.bootcamp.lab:8443":{"auth":"cXVheTpmYXJkaWFudEByZWRoYXQ="},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWJlNzk2YjY1LWM5NGEtNDRjMi05MjQyLTcwM2ZiYzYyNTA2NTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTVaamhsWmpRME16TmlNVEkwTnpCaVlUZGxaV0ZsWW1NME9XRmxOelE0TXlKOS5xcWlSWGNTR3NtMEVYMVlFLXNqWi1PRkN4Q0M0OE1GRVV3TDBMMmRKXy1QN0VZMXRYdlhZVzNidTl6WEVrMkRTTnN4R3B5WE52ay1oUS13TXhBamNET3drSU5tbjBtdVQzSk5IRUdhaFU0R2lCQlFNb0toUElrV2Y1U050bFF4djBVVnpGenE3QkV2b0lMa1F2R1hWTUR3eHEtOGdIWWNYTGgyQjJJNzItWDN6ekFzWmNhNzhHcGlSYkc2MWg3aS1kZWlKNW52eGlHYUM0N3FiM2l0WlhXUDdCYXBnSlhhdEh2Z0lXTmM0d01jZG1mUUMxR3FkTVNIMDJ3NXNpRUY1MWJweXZhektrYUdENU9RS0ZIS2NMUld5ekF6SEQtWVA1QUxLaHdsTWREdGJjczhkSVFiMkx6Q0tZYTZWaVN5WUEwYWFWZHY1V3IwT3ZteUUyNG1uVWNDNTR5MXc0bmVIVzg3NUZFd0stc0hiT2FOR01DajJUQTJqQTFyYkp3aWcyMHpGc0dzWnpvU284ZnFsUl9lMVhUd2FsZTJUTkM0V1IxWDV6dTlhT0lpSHVLTUdMV1lqUGo2aWJvQjM5MzBQa2JTYkx3VEpkTGFQdUxBYm5hUi1YOHlwVk05QXcxZXc0aEE5TTdmTmFaeTFXcUZOQUs5bGFiWUFWZExWcTlSNVpYYjJoRmdDZF82SEVJMHk1OU1qNFZfWkRkWE1xWW9uSUF6Tk5BVnN5ZFdPVTNWUDh6RGRpUVRRcmhjcWJKblBwTVhlamlMNkIyUzhyUHFkTXFPeVNhRzI2VWNlZU16TU5IV2NfTVRVRXpPTHVUOEJjQW5qYS1HZ2JoRWFlc0l0QzB1aWo0V190Rm5nZ2lXWW9MNG1LSkJmNmc5U3JSdFVFaXFsWU9CbkVjTQ=="}}}'

  type: kubernetes.io/dockerconfigjson

